config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'works/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "works#index"
  resources :works, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: :create 
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, genre: 'カテゴリー選択' },
    { id: 2, genre: 'ロボット' },
    { id: 3, genre: 'ミリタリー' },
    { id: 4, genre: 'カーモデル' },
    { id: 5, genre: 'バイクモデル' },
    { id: 6, genre: '鉄道模型' },
    { id: 7, genre: 'フィギュア' },
    { id: 8, genre: 'キャラクターモデル' },
    { id: 9, genre: 'ジオラマ' },
    { id: 10, genre: 'フルスクラッチ（オリジナル）' },
    { id: 11, genre: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :works

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :work

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :profile, presence: true
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'

  has_many :works
  has_many :comments
end

app/models/work.rb
class Work < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  has_one_attached :image
  belongs_to :category
  has_many :comments, dependent: :destroy

  validates :title, presence: true 
  validates :category_id, numericality: { other_than: 1 , message: "can't be blank"}
  validates :concept, presence: true 
  validates :explanation, presence: true
  validates :image, presence: true

  def was_attached?
    self.image.attached?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to work_path(@comment.work)
    else
      @work = @comment.work
      @comments = @work.comments
      render "works/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, work_id: params[:work_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
     @user = User.find(params[:id])
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

  def index
    @works = Work.includes(:user)
  end

  def new
   @work = Work.new
  end

  def create
     @work = Work.new(work_params)
     if @work.save
       redirect_to root_path
     else
       render :new
     end
  end

  def show
     @comment = Comment.new
     @comments = @work.comments
  end

  def edit
  end

  def update
    if @work.update(work_params)
     redirect_to work_path(@work)
    else
     render :edit
    end
  end

  def destroy
    if @work.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end
  
  private

  def work_params
    params.require(:work).permit(:title, :category_id, :concept, :explanation, :image).merge(user_id: current_user.id)
  end

  def set_work
    @work = Work.find(params[:id])
  end

  def contributor_confirmation
    unless current_user == @work.user
      redirect_to root_path 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MODELERS PLAZZA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.jpg", class: :logo), root_path %>
          </div>
          <div class="center">
          あなたの作品をみんなに共有しよう
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
              <%= link_to "投稿", new_work_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © MODELERS PLAZZA All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんの作品"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'works/work', collection: @user.works %>
      </div>
    </div>
  </div>
</div>

app/views/works/_form.html.erb
<%= form_with model: work, local: true do |f|%>
  <%= render 'devise/shared/error_messages', model: f.object %>
  <div class="field">
    <%= f.label :title, "作品タイトル" %><br />
    <%= f.text_field :title, id:"work_title" %>
  </div>

  <div class="weight-bold-text">
    作品カテゴリー
    <span class="indispensable">必須</span>
  </div>
  <%= f.collection_select(:category_id, Category.all, :id, :genre, {}, {class:"select-box", id:"work-category"}) %>

  <div class="field">
    <%= f.label :concept, "作品コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text, id:"work_concept" %>
  </div>
  <div class="field">
    <%= f.label :explanation, "作品説明" %><br />
    <%= f.text_area :explanation, class: :form__text, id:"work_explanation" %>
  </div>

  <div class="field">
    <%= f.label :image, "作品の画像" %><br />
    <%= f.file_field :image, id:"work_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/works/_work.html.erb
<div class="card">
  <%= link_to image_tag(work.image, class: :card__img ), work_path(work) %>
  <div class="card__body">
    <%= link_to work.title, work_path(work), class: :card__title %>
    <p class="card__summary">
      <%= work.category.genre %>
    </p>
    <%= link_to "by #{work.user.name}", user_path(work.user), class: :card__user %>
  </div>
</div>

app/views/works/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">作品投稿編集</h2>
      <%= render partial: "form", locals: { work: @work } %>
    </div>
  </div>
</div>

app/views/works/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、
         <%= link_to "#{current_user.name}さん", user_path(current_user), class: :greeting__link%>
      </div>
    <% end %>
    <div class="card__wrapper">
      <%= render partial: 'work', collection: @works %>
    </div>
  </div>
</main>

app/views/works/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "form", locals: { work: @work } %>
    </div>
  </div>
</div>

app/views/works/show.html.erb
<main class="main">
  <div class="inner">
    <div class="work__wrapper">
      <p class="work_hedding">
        <%= @work.title %>
      </p>
      <%= link_to "by #{@work.user.name}さんの作品", user_path(@work.user), class: :work__user %>
      <% if current_user == @work.user%>
        <div class="work__manage">
          <%= link_to "編集する", edit_work_path(@work), class: :work__btn %>
          <%= link_to "削除する", work_path(@work), method: :delete, class: :work__btn %>
        </div>
      <% end %>
      <div class="work__image">
        <%= image_tag @work.image %>
      </div>
      <div class="work__body">
        <div class="work__detail">
          <p class="detail__title">作品カテゴリー</p>
          <p class="detail__message">
            <%= @work.category.genre %>
          </p>
        </div>
        <div class="work__detail">
          <p class="detail__title">作品コンセプト</p>
          <p class="detail__message">
            <%= @work.concept %>
          </p>
          <p class="detail__title">作品説明</p>
          <p class="detail__explanation">
              _<%= @work.explanation %>
          </p>
        </div>
      </div>
      <div class="work__comments">
        <% if user_signed_in? %>
          <%= form_with model: [@work, @comment],local: true do |f|%>
            <div class="field">
              <%= f.label :content, "コメント" %><br />
              <%= f.text_field :content, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.content%>
              <%= link_to "（#{comment.user.name}）", user_path(comment.user), class: :comment_user %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>